### ISSUE TITLE
thank u for this x11

### ISSUE THREAD

**Issue by xoureldeen** [PangBaiWork/Dowork#6]
now i want to thank u bcuz this only x11 src it works for me with my projects and now i will try to implement mouse emulation with it

**Comment by PangBaiWork** [comment]
It's my pleasure.This x11 implementation relies on xvfb.It only transmits graphics frames and key events through the  x11 protocol, and to be honest, many details cannot be controlled in this way.Maybe it's a little ugly compared to the new version of termux-x11(this is more appropriate in other situations, such as proot and chroot, where I can install xvfb with the package manager and modify the xvfb in the container to achieve something else.).I'm not sure whether I should continue to maintain this project.I may need other people's opinions.

**Comment by xoureldeen** [comment]
Hi, thanks for reply, i understand but i have good idea to work together on this project, i trying to implement termux x11 to my projects but it not responding everytime without any reason, can we work on our x11 project? Check my github i have uncompleted projects like vterm, vectras vm, winux

Vterm is terminal based on terminal emulator by using proot
Vectras vm is friendly ui qemu emulator using proot
Winux is wine and steam and rpcs3 emulator (not finished cause i dont have good x11 src)

**Comment by xoureldeen** [comment]
I will appreciate if u accepted my request to work together

**Comment by xoureldeen** [comment]
I think that working on it is not difficult, but it requires more than one developer and we will study how it works
