### ISSUE TITLE
I needthe src code of bootstrap

### ISSUE THREAD

**Issue by xoureldeen** [PangBaiWork/Dowork#7]
I need the source codes of assets to change tmp path of x11 and else

**Comment by PangBaiWork** [comment]
This may take time, I almost forget the original compilation steps, I have an idea to create a new repository to hold a new x11 library, but I have been too busy lately, please give me some time.I tried to finish it before June.

**Comment by xoureldeen** [comment]
Ok bro take ur time, but please dont forgot bcuz i need it in my projects
