### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by xoureldeen** [PangBaiWork/Dowork#8]
please check this source code
https://github.com/epicstudios856/vectras-x11

the framebuffer sliced and the colors shifted wrong and i dont know why

**Comment by xoureldeen** [comment]
https://github.com/epicstudios856/vectras-x11/blob/main/app/src/main/cpp/xdraw.c

**Comment by PangBaiWork** [comment]
it looks like that you use bitmap to draw framebuffer.The performance cost will be higher than that of ANativeWindow.In  fact I've never tried this method,which may require some data conversion(due to the data format). You can get buffer fortmat form Ximage and the copy buffer in format form Xvfb_screen0 fd,there are some different between rgb and rgba too ，so it may need to add alpha channels manually.
I also thought about getting image data through fd at the beginning of the project. It will bring a better performance and avoid the memory defect of Ximage.But we need some tests before that.

**Comment by xoureldeen** [comment]
now i do what u say but image corrupted, sorry can u check it again?

**Comment by epicstudios856** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/ad532983-4422-4ca6-98ad-173f68366f03)

**Comment by xoureldeen** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/fe1fd23e-897f-4119-990f-ae0030dbce4d)

**Comment by xoureldeen** [comment]
i do what u say now, can u check the code and contribute pls

**Comment by PangBaiWork** [comment]
the fbfd is not just an array of pixels.It is a data buffer in xwd format.There are some relevant information https://en.wikipedia.org/wiki/Xwd.
I may start it at summer vacation.Or You can try to finish it first.

**Comment by PangBaiWork** [comment]
At present, the method of using x protocol to get ximage is available, this method does not need fd, and may be more suitable for a xserver.

**Comment by xoureldeen** [comment]
ok thanks alot, i will try this

**Comment by xoureldeen** [comment]
i need libX11.a source code to use XOpenDisplay(0)

**Comment by PangBaiWork** [comment]
> i need libX11.a source code to use XOpenDisplay(0)

You can build it with termux.

**Comment by xoureldeen** [comment]
How?, sorry im noob about x11 things

**Comment by PangBaiWork** [comment]
> How?, sorry im noob about x11 things

There are many ways to get x11 lib
you can build it with this build system https://github.com/termux/termux-packages.
or find libx11-static/stable installed by termux.
or directly use the elf file in my project.
If app  connect Xserver in TCP/IP these are all available.

**Comment by xoureldeen** [comment]
I thinks ur prebuilt libX11 uses co.pangbai.dowork, is thats right?

Now termux packages dosent build on my xubuntu server without reason

**Comment by PangBaiWork** [comment]
> I thinks ur prebuilt libX11 uses co.pangbai.dowork, is thats right?
> 
> Now termux packages dosent build on my xubuntu server without reason

you can use github action .there are automatic build scripts 
https://github.com/termux/termux-packages/actions/workflows/packages.yml

**Comment by xoureldeen** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/970cb9f2-43d0-47af-a039-15ab46d47843)

**Comment by xoureldeen** [comment]
libX11 libXau libX11-xcb libXcursor libdmcp libXext libXtst libxcb libandroid-support

**Comment by xoureldeen** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/bcfc7287-1201-46b8-a106-b43d0a518485)

**Comment by PangBaiWork** [comment]
the package called  libx11 ,not libX11.and you should edit your package name of app in https://github.com/termux/termux-packages/blob/master/scripts/properties.sh

**Comment by xoureldeen** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/167b1d31-a3cd-49ce-985a-656d67fa678c)

**Comment by xoureldeen** [comment]
https://github.com/epicstudios856/termux-packages/blob/master/scripts/properties.sh

**Comment by PangBaiWork** [comment]
> ![image](https://github.com/PangBaiWork/Dowork/assets/79816069/167b1d31-a3cd-49ce-985a-656d67fa678c)
> 

edit package.yml and remove "-I"

**Comment by xoureldeen** [comment]
ok thanks, i think now this time for using termux bootstraps instead of proot

**Comment by xoureldeen** [comment]
xvfb
ld.lld: error: undefined symbol: libandroid_shmget
>>> referenced by test_xcb_image_shm.c
>>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)

ld.lld: error: undefined symbol: libandroid_shmat
>>> referenced by test_xcb_image_shm.c
>>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)

ld.lld: error: undefined symbol: libandroid_shmctl
>>> referenced by test_xcb_image_shm.c
>>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:655: test_xcb_image_shm] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/builder/.termux-build/xcb-util-image/build/test'
make[1]: *** [Makefile:435: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/xcb-util-image/build'
make: *** [Makefile:367: all] Error 2
Error: Process completed with exit code 2.

**Comment by PangBaiWork** [comment]
> xvfb
> ld.lld: error: undefined symbol: libandroid_shmget
> >>> referenced by test_xcb_image_shm.c
> >>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)
> 
> ld.lld: error: undefined symbol: libandroid_shmat
> >>> referenced by test_xcb_image_shm.c
> >>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)
> 
> ld.lld: error: undefined symbol: libandroid_shmctl
> >>> referenced by test_xcb_image_shm.c
> >>>               test_xcb_image_shm-test_xcb_image_shm.o:(main)
> clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [Makefile:655: test_xcb_image_shm] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/home/builder/.termux-build/xcb-util-image/build/test'
> make[1]: *** [Makefile:435: all-recursive] Error 1
> make[1]: Leaving directory '/home/builder/.termux-build/xcb-util-image/build'
> make: *** [Makefile:367: all] Error 2
> Error: Process completed with exit code 2.
> 

add package libandroid-shmem

**Comment by epicstudios856** [comment]
always skipped 
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/60467858-1a60-4c22-8014-344a6a6136ad)

**Comment by xoureldeen** [comment]
after 50m

![image](https://github.com/PangBaiWork/Dowork/assets/79816069/5dcd35c0-c231-46c6-b0aa-68a34f1af504)

**Comment by PangBaiWork** [comment]
> after 50m
> 
> ![image](https://github.com/PangBaiWork/Dowork/assets/79816069/5dcd35c0-c231-46c6-b0aa-68a34f1af504)
> 

Consider pulling docker to compile locally

**Comment by xoureldeen** [comment]
![image](https://github.com/PangBaiWork/Dowork/assets/79816069/8186d612-7181-45d9-90f2-d8dbce2f3a0e)

**Comment by xoureldeen** [comment]
then?

**Comment by xoureldeen** [comment]
now the remaining thing is assets xvfb executable files

**Comment by PangBaiWork** [comment]
> now the remaining thing is assets xvfb executable files

add package xorg-server-xvfb，

and extract all deb packages and put them in assets (unexpectedly, my busy time may continue.there are still some details you need to deal with yourself.)

**Comment by xoureldeen** [comment]
Thx

**Comment by xoureldeen** [comment]
https://github.com/termux/termux-packages/issues/20336

**Comment by PangBaiWork** [comment]
> https://github.com/termux/termux-packages/issues/20336

I haven't had a problem like this before. you can try running the termux-package script in termux.termux-package is always updated, and the results of the latest scripts may be different from week to week.now, xvfb seems to depends on mesa, so the package built may be much larger than before.

**Comment by xoureldeen** [comment]
So what machine and os u built xvfb on and what u mean by termux.termux-package

**Comment by PangBaiWork** [comment]
> So what machine and os u built xvfb on and what u mean by termux.termux-package

![Screenshot_2024-05-28-13-47-25-748_com.termux.jpg](https://github.com/PangBaiWork/Dowork/assets/63479821/db5e4030-7ec4-41ba-b857-66e2fc2e10e3)

I'd like to say this, but this should not be the solution, because the package name cannot be changed at this time.As a matter of fact, I failed to build just now(in termux).termux-package maintainers may be needed to solve this problem(build mesa).

**Comment by xoureldeen** [comment]
so how u built xvfb in assets dir

**Comment by PangBaiWork** [comment]
> so how u built xvfb in assets dir
> 

I'm sorry. I've forgotten. I need some time to try.
