### ISSUE TITLE
Hehe sorry

### ISSUE THREAD

**Issue by xoureldeen** [PangBaiWork/Dowork#9]
![Screenshot_20240623-053408_Android Box86](https://github.com/PangBaiWork/Dowork/assets/79816069/8df91db3-befb-49e1-8a70-1e25e0b94e78)
I built my own packages using termux-packages
And busybox gives me this message on my termux fork (safe mode without termux bootatraps)

**Comment by PangBaiWork** [comment]
copy the lib to the lib path of prefix or use static link

**Comment by xoureldeen** [comment]
> copy the lib to the lib path of prefix or use static link


done but it shows help instead of input

can i install glibc on it?

**Comment by xoureldeen** [comment]
![Screenshot_20240624-044936_Vectras](https://github.com/PangBaiWork/Dowork/assets/79816069/f5825794-2671-40c1-90a6-562ef2f2100e)
![Screenshot_20240624-044930_Vterm](https://github.com/PangBaiWork/Dowork/assets/79816069/9ba9c2c8-5396-4ad2-9bb7-66fcab2ffa0a)


Mine dosent show shell like ur one

**Comment by PangBaiWork** [comment]
> ![Screenshot_20240624-044936_Vectras](https://github.com/PangBaiWork/Dowork/assets/79816069/f5825794-2671-40c1-90a6-562ef2f2100e)
> ![Screenshot_20240624-044930_Vterm](https://github.com/PangBaiWork/Dowork/assets/79816069/9ba9c2c8-5396-4ad2-9bb7-66fcab2ffa0a)
> 
> 
> Mine dosent show shell like ur one

related to your environment var and the configuration of compiling

**Comment by PangBaiWork** [comment]
I regret to inform you that the Termux build script for xvfb has undergone too many modifications, and I am currently unable to locate the old script. I have tried many methods, but it seems there is no quick way to build it now. Therefore, an xserver based on xvfb might not be feasible. I will pause my plans. You can try installing xvfb in a container to continue your project
